# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'InTouch' do

pod 'LayerKit', '~> 0.16.0'
pod 'Atlas', '~> 1.0.11'
pod 'Parse', '~> 1.8.0'
pod 'ParseUI', '~> 1.1.6'
pod 'SVProgressHUD', '~> 1.1.3'
pod 'XLForm'
pod 'JVFloatLabeledTextField'
pod 'TPKeyboardAvoiding'
pod 'SlackTextViewController'

end

target 'InTouchTests' do

end

target 'InTouchUITests' do

end

